### ISSUE TITLE
Animations of overlapping pieces of the same player transmorgify one into just a direction

### ISSUE THREAD

**Issue by jimmyfnugent** [jimmyfnugent/tic-tac-go#33]
If a player has two pieces converging on the same spot, one of them gets turned into an image of just its direction during the animation. This is because that's exactly what Space.updateImageResources is supposed to do.

**Comment by apmcleod** [comment]
This is because if they are both full pieces, when they are in the same space, a Piece will cover the other's direction. This can be solved by calling Piece.updateImageResourceFullPiece() before animation start.

Possibly, we may want to look into a Piece UI that doesn't have this problem, though I quite like the current look.
